Repository bbiyongbbiyong/bbiyong-server, pull requests merged in 2023-07, with the labels that each got.

#46 fix: ci 파일 수정
  .github/workflows/gradle.yml
  src/test/java/com/capstone/bbiyong/BbiyongApplicationTests.java
Labels: 🐛bug, ⚙️setting, ⚒️refactor

#48 fix: 커밋 메시지 오류 수정
  settings.gradle
Labels: 🐛fix

#50 config: cd 파일 부분 추가
  .github/workflows/ci.yml
Labels: ⚙️config, 💛cd

#53 fix: Code Deploy 옵션 오타 수정
  .github/workflows/cd.yml
Labels: 💛cd

#86 feat: 홈 화면 차트에 사용하는 데이터 분석 api 추가
  bbiyong-api/src/main/java/com/capstone/analytics/controller/AnalyticsController.java
  bbiyong-api/src/main/java/com/capstone/analytics/dto/ChartDataResponseDTO.java
  bbiyong-api/src/main/java/com/capstone/analytics/service/AnalyticsService.java
  bbiyong-domain/src/main/java/com/capstone/accident/repository/AccidentRepository.java
  bbiyong-domain/src/main/java/com/capstone/emerMsg/respository/EmerMsgRepository.java
  bbiyong-domain/src/main/java/com/capstone/metro/repository/MetroRepository.java
Labels: ✨feature

#85 feat: ID/PW 로그인
  bbiyong-api/build.gradle
  bbiyong-api/src/main/java/com/capstone/common/exception/ErrorCode.java
  bbiyong-api/src/main/java/com/capstone/member/controller/AuthController.java
  bbiyong-api/src/main/java/com/capstone/member/dto/MemberDto.java
  bbiyong-api/src/main/java/com/capstone/member/dto/request/JoinRequestDto.java
  bbiyong-api/src/main/java/com/capstone/member/dto/request/LoginRequestDto.java
  bbiyong-api/src/main/java/com/capstone/member/dto/resonse/MemberInfoResponseDto.java
  bbiyong-api/src/main/java/com/capstone/member/service/AuthService.java
  bbiyong-api/src/main/java/com/capstone/security/config/SecurityConfig.java
  bbiyong-api/src/main/java/com/capstone/security/filter/JwtTokenFilter.java
  bbiyong-api/src/main/java/com/capstone/security/service/CustomUserService.java
  bbiyong-api/src/main/java/com/capstone/security/util/CustomAuthenticationEntryPoint.java
  bbiyong-api/src/main/java/com/capstone/security/util/JwtTokenUtils.java
  bbiyong-api/src/main/resources/application-datasource.yml
  bbiyong-api/src/main/resources/application-settings.yml
  bbiyong-api/src/main/resources/application.yml
  bbiyong-domain/src/main/java/com/capstone/member/domain/Member.java
  bbiyong-domain/src/main/java/com/capstone/member/repository/MemberRepository.java
Labels: ✨feature

#88 fix: 회원 가입 시 response DTO 형태 변경 MemberDto -> MemberInfoResponseDto
  bbiyong-api/src/main/java/com/capstone/member/controller/AuthController.java
  bbiyong-api/src/main/java/com/capstone/member/dto/resonse/MemberInfoResponseDto.java
  bbiyong-api/src/main/java/com/capstone/member/service/AuthService.java
Labels: 🐛fix

#90 feat: health check를 위한 HealthController
  bbiyong-api/src/main/java/com/capstone/common/controller/HealthController.java
Labels: ✨feature

#92 fix: swagger server url 설정
  bbiyong-api/src/main/java/com/capstone/common/config/SwaggerConfig.java
  bbiyong-api/src/main/java/com/capstone/common/controller/SwaggerController.java
  bbiyong-api/src/main/resources/application-settings.yml
Labels: 🐛fix

#94 fix: 회원가입, 로그인 시 custom 에러 처리
  bbiyong-api/src/main/java/com/capstone/common/exception/ErrorCode.java
  bbiyong-api/src/main/java/com/capstone/member/controller/AuthController.java
  bbiyong-api/src/main/java/com/capstone/member/dto/request/JoinRequestDto.java
  bbiyong-api/src/main/java/com/capstone/member/dto/request/LoginRequestDto.java
  bbiyong-api/src/main/java/com/capstone/member/service/AuthService.java
  bbiyong-api/src/main/java/com/capstone/security/service/CustomUserService.java
  bbiyong-api/src/main/java/com/capstone/security/util/CustomAuthenticationEntryPoint.java
Labels: 🐛fix

#97 fix: JoinRequestDto, LoginRequestDto에서 사용자 아이디를 id 대신에 accountId로 변경
  bbiyong-api/src/main/java/com/capstone/member/controller/AuthController.java
  bbiyong-api/src/main/java/com/capstone/member/dto/request/JoinRequestDto.java
  bbiyong-api/src/main/java/com/capstone/member/dto/request/LoginRequestDto.java
Labels: 🐛fix

#99 chore: error log 주석 제거
  bbiyong-api/src/main/java/com/capstone/security/filter/JwtTokenFilter.java
Labels: 🐛fix

#104 fix: batch 모듈에도 swagger 설정 추가
  bbiyong-batch/src/main/java/com/capstone/common/config/SwaggerConfig.java
  bbiyong-batch/src/main/java/com/capstone/common/controller/HealthController.java
  bbiyong-batch/src/main/java/com/capstone/common/controller/SwaggerController.java
Labels: 🐛fix, ♻️refactor

#106 fix(batch): ErrorCode 추가
  bbiyong-batch/src/main/java/com/capstone/common/exception/ErrorCode.java
Labels: 🐛fix
